-- ============================================================================
-- 0001_core.sql — Common Workflows (everyone depends on this file)
--
-- Covers requirement rows "Registration, Login & SSO" and "Role & Admin
-- Activities": profiles, houses, house membership, roles, and the Row Level
-- Security helper functions every other migration builds on.
--
-- Do not edit this file after it has been pushed. Add a new numbered
-- migration instead — that is what keeps three people's schemas in sync.
-- ============================================================================

create extension if not exists "pgcrypto";  -- gen_random_uuid()

-- ── Enums ───────────────────────────────────────────────────────────────────
create type public.user_role as enum ('RESIDENT', 'LANDLORD', 'ADMIN');
create type public.membership_status as enum ('ACTIVE', 'PENDING', 'LEFT');

-- ── updated_at bookkeeping ──────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── profiles: one row per auth.users row ────────────────────────────────────
-- Supabase owns the auth.users table (email, password hash, OAuth identities).
-- Everything WE care about about a person lives here.
create table public.profiles (
  id                      uuid primary key references auth.users (id) on delete cascade,
  email                   text        not null,
  full_name               text        not null default '',
  phone                   text,
  avatar_url              text,
  role                    public.user_role not null default 'RESIDENT',
  emergency_contact_name  text,
  emergency_contact_phone text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create the profile the moment someone signs up (email/password OR
-- Google SSO), so no code path ever has to remember to do it.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── houses ──────────────────────────────────────────────────────────────────
create table public.houses (
  id                 uuid primary key default gen_random_uuid(),
  name               text        not null,
  address            text        not null,
  area               text,
  latitude           double precision,
  longitude          double precision,
  landlord_id        uuid references public.profiles (id) on delete set null,
  google_calendar_id text,  -- M3.6, Araf
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index houses_landlord_id_idx on public.houses (landlord_id);

create trigger houses_set_updated_at
  before update on public.houses
  for each row execute function public.set_updated_at();

-- ── house_members: who lives where, and who runs the house ──────────────────
create table public.house_members (
  id             uuid primary key default gen_random_uuid(),
  house_id       uuid not null references public.houses (id) on delete cascade,
  user_id        uuid not null references public.profiles (id) on delete cascade,
  role           public.user_role not null default 'RESIDENT',
  is_house_admin boolean not null default false,
  status         public.membership_status not null default 'ACTIVE',
  joined_at      timestamptz not null default now(),
  created_at     timestamptz not null default now(),
  unique (house_id, user_id)
);

create index house_members_user_id_idx on public.house_members (user_id);
create index house_members_house_id_idx on public.house_members (house_id);

-- ── RLS helper functions ────────────────────────────────────────────────────
-- These are SECURITY DEFINER on purpose: they read house_members while
-- BYPASSING its RLS. Without that, a policy on house_members that queries
-- house_members causes infinite recursion (error 42P17) — the single most
-- common Supabase mistake. Always ask membership questions through these.

create or replace function public.is_house_member(p_house_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.house_members
    where house_id = p_house_id and user_id = auth.uid() and status = 'ACTIVE'
  );
$$;

create or replace function public.is_house_admin(p_house_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.house_members
    where house_id = p_house_id
      and user_id = auth.uid()
      and status = 'ACTIVE'
      and is_house_admin = true
  )
  or exists (
    select 1 from public.houses
    where id = p_house_id and landlord_id = auth.uid()
  );
$$;

create or replace function public.is_platform_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'ADMIN'
  );
$$;

-- ── Row Level Security ──────────────────────────────────────────────────────
alter table public.profiles      enable row level security;
alter table public.houses        enable row level security;
alter table public.house_members enable row level security;

-- profiles: readable by any signed-in user, writable only by their owner.
-- Restricting reads to "people you share a house with" would be tighter, but
-- names have to render in expenses, votes, chores and join requests, and the
-- membership check would need a subquery on every profile read. Names and
-- avatars are the only fields here worth hiding; if you later add anything
-- sensitive, narrow this policy with a column grant.
create policy "profiles readable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "users update own profile"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- houses: members, the landlord, and platform admins.
create policy "house visible to members and landlord"
  on public.houses for select
  to authenticated
  using (
    public.is_house_member(id)
    or landlord_id = auth.uid()
    or public.is_platform_admin()
  );

create policy "landlords create houses"
  on public.houses for insert
  to authenticated
  with check (landlord_id = auth.uid());

create policy "house admins update house"
  on public.houses for update
  to authenticated
  using (public.is_house_admin(id) or public.is_platform_admin())
  with check (public.is_house_admin(id) or public.is_platform_admin());

-- house_members: see your own rows, plus everyone in a house you're in.
create policy "membership rows visible to housemates"
  on public.house_members for select
  to authenticated
  using (user_id = auth.uid() or public.is_house_member(house_id) or public.is_platform_admin());

create policy "users request to join houses"
  on public.house_members for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "house admins manage membership"
  on public.house_members for update
  to authenticated
  using (public.is_house_admin(house_id) or user_id = auth.uid())
  with check (public.is_house_admin(house_id) or user_id = auth.uid());

create policy "house admins remove members"
  on public.house_members for delete
  to authenticated
  using (public.is_house_admin(house_id) or user_id = auth.uid());
